# Created by JingBh
#
# This file is used to create a conda environment
# that contains all the dependencies.
#
# Usage:
# $ conda env create -n dig-python -f conda-env.yml
# $ conda activate dig-python
#
# Note:
# Due to a macOS restriction, macOS users should
# run the following commands to make numpy work:
# $ conda remove -y mkl mkl-service
# $ conda install -y nomkl
# $ conda env update --file conda-env.yml
# (Ref: https://docs.anaconda.com/mkl-optimizations)

name: dig-python
channels:
  - defaults
dependencies:
  - keras==2.3.1
  - tensorflow==2.0.0
  - tensorflow-estimator==2.0.0
  - h5py~=2.0
  - flask
